version: '2'
services:
  kolekti:
    image: sbonhomme/kolekti-base
    volumes:
      - "${KOLEKTI_SRC}:/kolekti/src:rw"
      - "${KOLEKTI_STATIC}:/static:rw"
      - "${KOLEKTI_SVN}:/svn:rw"
      - "${KOLEKTI_PROJECTS}:/projects:rw"
      - "${KOLEKTI_DB}:/db:rw"
      - "${KOLEKTI_LOG}:/var/log:rw"
      - "${KOLEKTI_FONTS}:/usr/share/fonts/extra"
      - "${KOLEKTI_PRIVATE}:/private"
      - "${KOLEKTI_PRIVATE}/prince:/usr/lib/prince/license/:ro"
    ports:
      - "8000"
    environment:
      PYTHONPATH: /kolekti/src
      GUNICORN_OPTS:
      UID:
      GID:
      KOLEKTI_DBFILE: /db/db.sqlite3
      KOLEKTI_EMAIL_HOST:
      KOLEKTI_EMAIL_PORT:
      KOLEKTI_EMAIL_USER:
      KOLEKTI_EMAIL_PASSWORD:
      KOLEKTI_EMAIL_FROM:
      KOLEKTI_DEBUG:
      VIRTUAL_HOST:
  front:
    # the front is an apache, acting as a proxy to wsgi, serving static content and doing svn
    image: sbonhomme/kolekti-front
    volumes:
      - "${KOLEKTI_STATIC}:/static:ro"
      - "${KOLEKTI_LOG}:/var/log:rw"
      - "${KOLEKTI_SVN}:/svn:rw"
      - "${KOLEKTI_PRIVATE}:/private:ro"
    ports:
      - "${EXTERNAL_PORT}:80"
    links:
      - kolekti
    environment:
      KOLEKTI_DBFILE: /db/db.sqlite3
      UID:
      GID:
