version: '3'
services:
  kolekti:
    build: .
    image: kolekti-cli
    volumes:
      - "${KOLEKTI_PROJECT}:/project:rw"
      - "${KOLEKTI_PROJECT}/kolekti/fonts:/usr/share/fonts/extra"
      - "${KOLEKTI_PROJECT}/kolekti/princexml:/usr/lib/prince/license"
    environment:
      PYTHONPATH: /usr/lib/kolekti

