#!/bin/bash

# POST-COMMIT HOOK
#
# The post-commit hook is invoked after a commit.  Subversion runs
# this hook by invoking a program (script, executable, binary, etc.)
# named 'post-commit' (for which this file is a template) with the
# following ordered arguments:
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)
#
# The default working directory for the invocation is undefined, so
# the program should set one explicitly if it cares.
#
# Because the commit has already completed and cannot be undone,
# the exit code of the hook program is ignored.  The hook program
# can use the 'svnlook' utility to help it examine the
# newly-committed tree.
#
# On a Unix system, the normal procedure is to have 'post-commit'
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that 'post-commit' must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
# On a Windows system, you should name the hook program
# 'post-commit.bat' or 'post-commit.exe',
# but the basic idea is the same.
#
# The hook program typically does not inherit the environment of
# its parent process.  For example, a common problem is for the
# PATH environment variable to not be set to its usual value, so
# that subprograms fail to launch unless invoked via absolute path.
# If you're having unexpected problems with a hook program, the
# culprit may be unusual (or missing) environment variables.
#
# Here is an example hook script, for a Unix /bin/sh interpreter.
# For more examples and pre-written hooks, see those in
# /usr/share/subversion/hook-scripts, and in the repository at
# http://svn.apache.org/repos/asf/subversion/trunk/tools/hook-scripts/ and
# http://svn.apache.org/repos/asf/subversion/trunk/contrib/hook-scripts/

LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.UTF-8
REPOS="$1"
REPO=$(basename $REPOS)
REV="$2"
OWNER=$(whoami)
PROJECT_BASE="@project_basedir@/projects/"
MANAGE_LOCATION="/usr/shared/pyshared/kolektiserver/manage.py"
KOLEKTI_APPDIR="/usr/shared/pyshared/kolektiserver/"
KOLEKTI_APP="kolektiserver"
# should we update kolekti's checkout ?
if [ -e /var/lock/kolekti/$REPO -o -e /tmp/kolekti_svn_${REPO}_lock ]
then
	LANG=fr_FR.UTF-8 /usr/bin/svn update ${PROJECT_BASE}${REPO} >> /var/lock/kolekti/post-commit 2>&1
	LANG=fr_FR.UTF-8 /usr/bin/svn log ${PROJECT_BASE}${REPO} -r $REV -v | egrep "^   (A|D|M).*" | python ${MANAGE_LOCATION} -c syncprojectsvn >> /tmp/syncprojectsvn.log
	rm /var/lock/kolekti/$REPO /tmp/kolekti_svn_${REPO}_lock
fi

exit 0

